---
name: CI
on:
  push:
    branches:
      - astro
  pull_request:
    branches:
      - astro
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copying over the files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          rm: true
          source: .
          target: /home/BSChallenger.Website
      - name: Building the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script_stop: true
          script: |
            cd "/home"
            cd "BSChallenger.Website"
            astro build
            pm2 delete website -s
            NODE_ENV=production pm2 start --name <app name> npm -- start
